{{- if and .Values.ingress.enabled ( eq .Values.ingress.kind "ingress" ) }}
{{- $ingressHosts := .Values.ingress.hosts | default "*" }}
{{- $uri_prefix := .Values.ingress.uri_prefix | default "/" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: {{ include "application.fullname" . }}
spec:
  rules:
  - host: {{ $ingressHosts }}
    http:
      paths:
      - path: {{ $uri_prefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "application.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}